import { availableResources } from "../game-information/resources";
import { Building } from "./buildings";
import { TheBuilding } from "./the-building";

interface AvailableBuildings {
	[key: string]: Building;
}
export const availableBuildings: AvailableBuildings = {
	coalMine: new TheBuilding({
		name: "coalMine",
		namePretty: "Coal Mine",
		mapIcon: "C",
		baseCost: 100,
		inputs: [],
		outputs: [{ resource: availableResources.coal, amount: 5 }],
		pointingBuilding: false,
		buildingFunctions: ["output"],
		buildingResourceMine: availableResources.coal,
	}),
	ironMine: new TheBuilding({
		name: "ironMine",
		namePretty: "Iron Mine",
		mapIcon: "Fe",
		baseCost: 125,
		inputs: [],
		outputs: [{ resource: availableResources.iron, amount: 2 }],
		pointingBuilding: false,
		buildingFunctions: ["output"],
		buildingResourceMine: availableResources.iron,
	}),
	copperMine: new TheBuilding({
		name: "copperMine",
		namePretty: "Copper Mine",
		mapIcon: "Cu",
		baseCost: 150,
		inputs: [],
		outputs: [{ resource: availableResources.copper, amount: 3 }],
		pointingBuilding: false,
		buildingFunctions: ["output"],
		buildingResourceMine: availableResources.copper,
	}),
	rubberPlant: new TheBuilding({
		name: "rubberPlant",
		namePretty: "Rubber Plant",
		mapIcon: "R",
		baseCost: 25,
		inputs: [],
		outputs: [{ resource: availableResources.rubber, amount: 1 }],
		pointingBuilding: false,
		buildingFunctions: ["output"],
		buildingResourceMine: availableResources.rubber,
	}),
	steelMill: new TheBuilding({
		name: "steelMill",
		namePretty: "Steel Mill",
		mapIcon: "St",
		baseCost: 300,
		inputs: [
			{ resource: availableResources.iron, amount: 5 },
			{ resource: availableResources.coal, amount: 1 },
		],
		outputs: [{ resource: availableResources.steel, amount: 6 }],
		pointingBuilding: false,
		buildingFunctions: ["input", "output"],
	}),
	electronicsFactory: new TheBuilding({
		name: "electronicsFactory",
		namePretty: "Electronics Factory",
		mapIcon: "E",
		baseCost: 800,
		inputs: [
			{ resource: availableResources.copper, amount: 2 },
			{ resource: availableResources.iron, amount: 1 },
		],
		outputs: [{ resource: availableResources.electronics, amount: 10 }],
		pointingBuilding: false,
		buildingFunctions: ["input", "output"],
	}),
	machineFactory: new TheBuilding({
		name: "machineFactory",
		namePretty: "Machine Factory",
		mapIcon: "M",
		baseCost: 1000,
		inputs: [
			{ resource: availableResources.steel, amount: 3 },
			{ resource: availableResources.electronics, amount: 2 },
			{ resource: availableResources.rubber, amount: 1 },
		],
		outputs: [{ resource: availableResources.machine, amount: 10 }],
		pointingBuilding: false,
		buildingFunctions: ["input", "output"],
	}),
	powerPlant: new TheBuilding({
		name: "powerPlant",
		namePretty: "Power Plant",
		mapIcon: "P",
		baseCost: 180,
		inputs: [{ resource: availableResources.coal, amount: 2 }],
		outputs: [],
		pointingBuilding: false,
		buildingFunctions: ["spreadThroughput"],
		buildingFunctionDescription: [
			"All buildings around the Power Plant have throughput increased by 10%. One building can be affected by multiple powerplants.",
		],
	}),
	market: new TheBuilding({
		name: "market",
		namePretty: "Market",
		mapIcon: "M€",
		baseCost: 100,
		inputs: [],
		outputs: [],
		pointingBuilding: true,
		buildingFunctions: ["buysFromDirection"],
		buildingFunctionDescription: [
			"Buys resources from the direction of the building. This is only way to sell the resources. Amount of resources sold is equal to the base output of the building.",
			"To change the direction, click R while building is selected.",
			"Every building around the Market,  has buy price of resource decreased by 15%, this effect stacks.",
		],
	}),
	bulldozer: new TheBuilding({
		name: "bulldozer",
		namePretty: "Bulldozer",
		mapIcon: "B",
		baseCost: 0,
		inputs: [],
		outputs: [],
		pointingBuilding: false,
		buildingFunctions: ["bulldozeBuilding"],
		buildingFunctionDescription: [
			"If placed on another building, that building will be destroyed.",
			"No refunds for destroyed building costs.",
		],
	}),
};
