import { availableResources } from "../game-information/resources";
import { Building } from "./buildings";
import { TheBuilding } from "./the-building";

interface AvailableBuildings {
	[key: string]: Building;
}
export const availableBuildings: AvailableBuildings = {
	coalMine: new TheBuilding({
		name: "coalMine",
		namePretty: "Coal Mine",
		mapIcon: "C",
		baseCost: 100,
		inputs: [],
		outputs: [{ resource: availableResources.coal, amount: 5 }],
		pointingBuilding: false,
		buildingFunction: "output",
		buildingResourceMine: availableResources.coal,
	}),
	ironMine: new TheBuilding({
		name: "ironMine",
		namePretty: "Iron Mine",
		mapIcon: "Fe",
		baseCost: 125,
		inputs: [],
		outputs: [{ resource: availableResources.iron, amount: 2 }],
		pointingBuilding: false,
		buildingFunction: "output",
		buildingResourceMine: availableResources.iron,
	}),
	copperMine: new TheBuilding({
		name: "copperMine",
		namePretty: "Copper Mine",
		mapIcon: "Cu",
		baseCost: 150,
		inputs: [],
		outputs: [{ resource: availableResources.copper, amount: 3 }],
		pointingBuilding: false,
		buildingFunction: "output",
		buildingResourceMine: availableResources.copper,
	}),
	rubberPlant: new TheBuilding({
		name: "rubberPlant",
		namePretty: "Rubber Plant",
		mapIcon: "R",
		baseCost: 25,
		inputs: [],
		outputs: [{ resource: availableResources.rubber, amount: 1 }],
		pointingBuilding: false,
		buildingFunction: "output",
		buildingResourceMine: availableResources.rubber,
	}),
	steelMill: new TheBuilding({
		name: "steelMill",
		namePretty: "Steel Mill",
		mapIcon: "St",
		baseCost: 300,
		inputs: [
			{ resource: availableResources.iron, amount: 5 },
			{ resource: availableResources.coal, amount: 1 },
		],
		outputs: [{ resource: availableResources.steel, amount: 6 }],
		pointingBuilding: false,
		buildingFunction: "inputOutput",
	}),
	electronicsFactory: new TheBuilding({
		name: "electronicsFactory",
		namePretty: "Electronics Factory",
		mapIcon: "E",
		baseCost: 800,
		inputs: [
			{ resource: availableResources.copper, amount: 2 },
			{ resource: availableResources.iron, amount: 1 },
		],
		outputs: [{ resource: availableResources.electronics, amount: 10 }],
		pointingBuilding: false,
		buildingFunction: "inputOutput",
	}),
	machineFactory: new TheBuilding({
		name: "machineFactory",
		namePretty: "Machine Factory",
		mapIcon: "M",
		baseCost: 1000,
		inputs: [
			{ resource: availableResources.steel, amount: 3 },
			{ resource: availableResources.electronics, amount: 2 },
			{ resource: availableResources.rubber, amount: 1 },
		],
		outputs: [{ resource: availableResources.machine, amount: 10 }],
		pointingBuilding: false,
		buildingFunction: "inputOutput",
	}),
	market: new TheBuilding({
		name: "market",
		namePretty: "Market",
		mapIcon: "M€",
		baseCost: 100,
		inputs: [],
		outputs: [],
		pointingBuilding: true,
		buildingFunction: "buysFromDirection",
		buildingFunctionDescription: [
			"Buys resources from the direction of the building. This is only way to sell the resources.",
			"To change the direction, click R while building is selected.",
		],
	}),
	bulldozer: new TheBuilding({
		name: "bulldozer",
		namePretty: "Bulldozer",
		mapIcon: "B",
		baseCost: 0,
		inputs: [],
		outputs: [],
		pointingBuilding: false,
		buildingFunction: "bulldozeBuilding",
		buildingFunctionDescription: [
			"If placed on another building, that building will be destroyed.",
			"No refunds for destroyed building costs.",
		],
	}),
};
